## 1. Clean raw data

In [22]:
import pandas as pd
df_info = pd.read_csv("all_stock.csv")

In [23]:
df_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3975 entries, 0 to 3974
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         3975 non-null   int64
 1   stock_id           3975 non-null   object
 2   stock_name         3975 non-null   object
 3   industry_category  3975 non-null   object
 4   list_type          3975 non-null   object
 5   list_date          3943 non-null   object
 6   raw                3975 non-null   object
dtypes: int64(1), object(6)
memory usage: 217.5+ KB

In [24]:
df_info = df_info.loc[:, ~df_info.columns.str.contains(r"^Unnamed")]
df_info.columns = df_info.columns.str.strip()

In [25]:
df_info

,stock_id,stock_name,industry_category,list_type,list_date,raw
0,3687,歐買尬,文化創意業,tpex,2020-06-03,"{'industry_category': '文化創意業', 'stock_id': '36..."
1,5481,新華,電子零組件業,tpex,2020-06-03,"{'industry_category': '電子零組件業', 'stock_id': '5..."
2,3629,地心引力,光電業,tpex,2020-06-03,"{'industry_category': '光電業', 'stock_id': '3629..."
3,5450,寶聯通,電腦及週邊設備業,tpex,2020-06-03,"{'industry_category': '電腦及週邊設備業', 'stock_id': ..."
4,6238,勝麗,其他電子類,tpex,2020-06-13,"{'industry_category': '其他電子類', 'stock_id': '62..."
...,...,...,...,...,...,...
3970,BiotechnologyMedicalCare,生技醫療類指數,Index,twse,NaN,"{'industry_category': 'Index', 'stock_id': 'Bi..."
3971,Automobile,汽車類指數,Index,twse,NaN,"{'industry_category': 'Index', 'stock_id': 'Au..."
3972,TPEx,櫃買指數,大盤,tpex,NaN,"{'industry_category': '大盤', 'stock_id': 'TPEx'..."
3973,Food,食品類指數,Index,twse,NaN,"{'industry_category': 'Index', 'stock_id': 'Fo..."
3974,TradingConsumersGoods,貿易百貨類指數,Index,twse,NaN,"{'industry_category': 'Index', 'stock_id': 'Tr..."

In [26]:
dup_id = df_info.groupby('stock_id')['stock_name'].nunique()
dup_id = dup_id[dup_id > 1]  # 出現多於1個名稱的ID
problem_id = df_info[df_info['stock_id'].isin(dup_id.index)]
print(problem_id)

     stock_id  stock_name industry_category list_type   list_date  \
3        5450         寶聯通          電腦及週邊設備業      tpex  2020-06-03
72       1443          立益              紡織纖維      twse  2021-06-01
79       5345          天揚            電子零組件業      tpex  2021-06-12
81       3219        倚強股份              半導體業      tpex  2021-06-12
83       5604         中連貨               航運業      tpex  2021-06-12
109      8080        永利聯合            電子零組件業      tpex  2022-06-03
124      6869      雲豹能源-創             創新板股票      twse  2023-03-17
125      6873      泓德能源-創             創新板股票      twse  2023-03-17
127      2432          倚天             通信網路業      twse  2023-05-30
137      3522          御頂              觀光事業      tpex  2023-06-29
155      2718          晶悅              觀光事業      tpex  2023-06-29
158      2724       富驛-KY              觀光事業      tpex  2023-06-29
159      5278          尚凡             電子商務業      tpex  2023-06-29
164      6763        綠界科技             電子商務業      tpex  2023-06-29
190      3171          新洲              貿易百貨      tpex  2023-06-29
266      2718          晶悅              觀光餐旅      tpex  2023-07-05
270      8087         華鎂鑫               光電業      tpex  2023-07-05
278      8476          台境                其他      tpex  2023-07-05
287      8476          台境             綠能環保類      tpex  2023-11-02
301      4419          元勝              紡織纖維      tpex  2024-06-05
321      6869        雲豹能源             創新版股票      twse  2024-11-25
322      6873        泓德能源             創新版股票      twse  2024-11-25
323      6757      台灣虎航-創             創新版股票      twse  2024-11-28
346      2432      倚天酷碁-創             創新版股票      twse  2024-12-04
416      6902  GOGOLOOK-創             創新版股票      twse  2024-12-04
649      6902  GOGOLOOK-創             創新板股票      twse  2025-05-16
661      2724       藝舍-KY              觀光餐旅      tpex  2025-06-01
1035     5278         尚凡*             數位雲端類      tpex  2025-09-30
1036     5345          馥鴻                其他      tpex  2025-09-30
1260     5450          南良                其他      tpex  2025-09-30
1335     5604          中連                其他      tpex  2025-09-30
1429     8080          泰霖              建材營造      tpex  2025-09-30
1564     8087        麗升能源             綠能環保類      tpex  2025-09-30
1609     8476         台境*              綠能環保      twse  2025-09-30
1826     6757        台灣虎航               航運業      twse  2025-09-30
1830     6763       綠界科技*             數位雲端類      tpex  2025-09-30
2007     6902    GOGOLOOK              數位雲端      twse  2025-09-30
2135     6869        雲豹能源              綠能環保      twse  2025-09-30
2138     6873        泓德能源              綠能環保      twse  2025-09-30
2460     2432      倚天酷碁-創             創新板股票      twse  2025-09-30
2461     2432      倚天酷碁-創              電子工業      twse  2025-09-30
2462     2432      倚天酷碁-創          電腦及週邊設備業      twse  2025-09-30
2899     1443        立益物流                其他      twse  2025-09-30
3246     3522          御嵿              觀光餐旅      tpex  2025-09-30
3392     4419        皇家美食              觀光餐旅      tpex  2025-09-30
3528     2724       藝舍-KY                其他      tpex  2025-09-30
3555     2718        全心投控              建材營造      tpex  2025-09-30
3809     3171        炎洲流通             居家生活類      tpex  2025-09-30
3826     3219         倚強科             其他電子類      tpex  2025-09-30

                                                    raw
3     {'industry_category': '電腦及週邊設備業', 'stock_id': ...
72    {'industry_category': '紡織纖維', 'stock_id': '144...
79    {'industry_category': '電子零組件業', 'stock_id': '5...
81    {'industry_category': '半導體業', 'stock_id': '321...
83    {'industry_category': '航運業', 'stock_id': '5604...
109   {'industry_category': '電子零組件業', 'stock_id': '8...
124   {'industry_category': '創新板股票', 'stock_id': '68...
125   {'industry_category': '創新板股票', 'stock_id': '68...
127   {'industry_category': '通信網路業', 'stock_id': '24...
137   {'industry_category': '觀光事業', 'stock_id': '352...
155   {'industry_category': '觀光事業', 'stock_id': '271...
158   {'industry_category': '觀光事業', 'stock_id': '272...
159   {'industry_category': '電子商務業', 'stock_id': '52...
164   {'industry_category': '電子商務業', 'stock_id': '67...
190   {'industry_category': '貿易百貨', 'stock_id': '317...
266   {'industry_category': '觀光餐旅', 'stock_id': '271...
270   {'industry_category': '光電業', 'stock_id': '8087...
278   {'industry_category': '其他', 'stock_id': '8476'...
287   {'industry_category': '綠能環保類', 'stock_id': '84...
301   {'industry_category': '紡織纖維', 'stock_id': '441...
321   {'industry_category': '創新版股票', 'stock_id': '68...
322   {'industry_category': '創新版股票', 'stock_id': '68...
323   {'industry_category': '創新版股票', 'stock_id': '67...
346   {'industry_category': '創新版股票', 'stock_id': '24...
416   {'industry_category': '創新版股票', 'stock_id': '69...
649   {'industry_category': '創新板股票', 'stock_id': '69...
661   {'industry_category': '觀光餐旅', 'stock_id': '272...
1035  {'industry_category': '數位雲端類', 'stock_id': '52...
1036  {'industry_category': '其他', 'stock_id': '5345'...
1260  {'industry_category': '其他', 'stock_id': '5450'...
1335  {'industry_category': '其他', 'stock_id': '5604'...
1429  {'industry_category': '建材營造', 'stock_id': '808...
1564  {'industry_category': '綠能環保類', 'stock_id': '80...
1609  {'industry_category': '綠能環保', 'stock_id': '847...
1826  {'industry_category': '航運業', 'stock_id': '6757...
1830  {'industry_category': '數位雲端類', 'stock_id': '67...
2007  {'industry_category': '數位雲端', 'stock_id': '690...
2135  {'industry_category': '綠能環保', 'stock_id': '686...
2138  {'industry_category': '綠能環保', 'stock_id': '687...
2460  {'industry_category': '創新板股票', 'stock_id': '24...
2461  {'industry_category': '電子工業', 'stock_id': '243...
2462  {'industry_category': '電腦及週邊設備業', 'stock_id': ...
2899  {'industry_category': '其他', 'stock_id': '1443'...
3246  {'industry_category': '觀光餐旅', 'stock_id': '352...
3392  {'industry_category': '觀光餐旅', 'stock_id': '441...
3528  {'industry_category': '其他', 'stock_id': '2724'...
3555  {'industry_category': '建材營造', 'stock_id': '271...
3809  {'industry_category': '居家生活類', 'stock_id': '31...
3826  {'industry_category': '其他電子類', 'stock_id': '32...

In [27]:
df = df_info.copy()

## preprocessing

In [28]:
df['stock_id'] = df['stock_id'].astype(str).str.strip()
df['stock_name'] = df['stock_name'].astype(str).str.strip()
df['list_type'] = df['list_type'].astype(str).str.strip()
df['list_date'] = pd.to_datetime(df['list_date'], errors='coerce')

df = df.drop_duplicates()

In [29]:
df

,stock_id,stock_name,industry_category,list_type,list_date,raw
0,3687,歐買尬,文化創意業,tpex,2020-06-03,"{'industry_category': '文化創意業', 'stock_id': '36..."
1,5481,新華,電子零組件業,tpex,2020-06-03,"{'industry_category': '電子零組件業', 'stock_id': '5..."
2,3629,地心引力,光電業,tpex,2020-06-03,"{'industry_category': '光電業', 'stock_id': '3629..."
3,5450,寶聯通,電腦及週邊設備業,tpex,2020-06-03,"{'industry_category': '電腦及週邊設備業', 'stock_id': ..."
4,6238,勝麗,其他電子類,tpex,2020-06-13,"{'industry_category': '其他電子類', 'stock_id': '62..."
...,...,...,...,...,...,...
3970,BiotechnologyMedicalCare,生技醫療類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Bi..."
3971,Automobile,汽車類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Au..."
3972,TPEx,櫃買指數,大盤,tpex,NaT,"{'industry_category': '大盤', 'stock_id': 'TPEx'..."
3973,Food,食品類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Fo..."
3974,TradingConsumersGoods,貿易百貨類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Tr..."

In [30]:
id_multi_names = (df.groupby('stock_id')['stock_name']
                    .nunique().sort_values(ascending=False))
id_multi_names = id_multi_names[id_multi_names > 1]

# 列出詳細行
rows_id_multi = df[df['stock_id'].isin(id_multi_names.index)]\
                .sort_values(['stock_id','list_date','stock_name'])

In [31]:
rows_id_multi

,stock_id,stock_name,industry_category,list_type,list_date,raw
72,1443,立益,紡織纖維,twse,2021-06-01,"{'industry_category': '紡織纖維', 'stock_id': '144..."
2899,1443,立益物流,其他,twse,2025-09-30,"{'industry_category': '其他', 'stock_id': '1443'..."
127,2432,倚天,通信網路業,twse,2023-05-30,"{'industry_category': '通信網路業', 'stock_id': '24..."
346,2432,倚天酷碁-創,創新版股票,twse,2024-12-04,"{'industry_category': '創新版股票', 'stock_id': '24..."
2460,2432,倚天酷碁-創,創新板股票,twse,2025-09-30,"{'industry_category': '創新板股票', 'stock_id': '24..."
2461,2432,倚天酷碁-創,電子工業,twse,2025-09-30,"{'industry_category': '電子工業', 'stock_id': '243..."
2462,2432,倚天酷碁-創,電腦及週邊設備業,twse,2025-09-30,"{'industry_category': '電腦及週邊設備業', 'stock_id': ..."
155,2718,晶悅,觀光事業,tpex,2023-06-29,"{'industry_category': '觀光事業', 'stock_id': '271..."
266,2718,晶悅,觀光餐旅,tpex,2023-07-05,"{'industry_category': '觀光餐旅', 'stock_id': '271..."
3555,2718,全心投控,建材營造,tpex,2025-09-30,"{'industry_category': '建材營造', 'stock_id': '271..."
158,2724,富驛-KY,觀光事業,tpex,2023-06-29,"{'industry_category': '觀光事業', 'stock_id': '272..."
661,2724,藝舍-KY,觀光餐旅,tpex,2025-06-01,"{'industry_category': '觀光餐旅', 'stock_id': '272..."
3528,2724,藝舍-KY,其他,tpex,2025-09-30,"{'industry_category': '其他', 'stock_id': '2724'..."
190,3171,新洲,貿易百貨,tpex,2023-06-29,"{'industry_category': '貿易百貨', 'stock_id': '317..."
3809,3171,炎洲流通,居家生活類,tpex,2025-09-30,"{'industry_category': '居家生活類', 'stock_id': '31..."
81,3219,倚強股份,半導體業,tpex,2021-06-12,"{'industry_category': '半導體業', 'stock_id': '321..."
3826,3219,倚強科,其他電子類,tpex,2025-09-30,"{'industry_category': '其他電子類', 'stock_id': '32..."
137,3522,御頂,觀光事業,tpex,2023-06-29,"{'industry_category': '觀光事業', 'stock_id': '352..."
3246,3522,御嵿,觀光餐旅,tpex,2025-09-30,"{'industry_category': '觀光餐旅', 'stock_id': '352..."
301,4419,元勝,紡織纖維,tpex,2024-06-05,"{'industry_category': '紡織纖維', 'stock_id': '441..."
3392,4419,皇家美食,觀光餐旅,tpex,2025-09-30,"{'industry_category': '觀光餐旅', 'stock_id': '441..."
159,5278,尚凡,電子商務業,tpex,2023-06-29,"{'industry_category': '電子商務業', 'stock_id': '52..."
1035,5278,尚凡*,數位雲端類,tpex,2025-09-30,"{'industry_category': '數位雲端類', 'stock_id': '52..."
79,5345,天揚,電子零組件業,tpex,2021-06-12,"{'industry_category': '電子零組件業', 'stock_id': '5..."
1036,5345,馥鴻,其他,tpex,2025-09-30,"{'industry_category': '其他', 'stock_id': '5345'..."
3,5450,寶聯通,電腦及週邊設備業,tpex,2020-06-03,"{'industry_category': '電腦及週邊設備業', 'stock_id': ..."
1260,5450,南良,其他,tpex,2025-09-30,"{'industry_category': '其他', 'stock_id': '5450'..."
83,5604,中連貨,航運業,tpex,2021-06-12,"{'industry_category': '航運業', 'stock_id': '5604..."
1335,5604,中連,其他,tpex,2025-09-30,"{'industry_category': '其他', 'stock_id': '5604'..."
323,6757,台灣虎航-創,創新版股票,twse,2024-11-28,"{'industry_category': '創新版股票', 'stock_id': '67..."
1826,6757,台灣虎航,航運業,twse,2025-09-30,"{'industry_category': '航運業', 'stock_id': '6757..."
164,6763,綠界科技,電子商務業,tpex,2023-06-29,"{'industry_category': '電子商務業', 'stock_id': '67..."
1830,6763,綠界科技*,數位雲端類,tpex,2025-09-30,"{'industry_category': '數位雲端類', 'stock_id': '67..."
124,6869,雲豹能源-創,創新板股票,twse,2023-03-17,"{'industry_category': '創新板股票', 'stock_id': '68..."
321,6869,雲豹能源,創新版股票,twse,2024-11-25,"{'industry_category': '創新版股票', 'stock_id': '68..."
2135,6869,雲豹能源,綠能環保,twse,2025-09-30,"{'industry_category': '綠能環保', 'stock_id': '686..."
125,6873,泓德能源-創,創新板股票,twse,2023-03-17,"{'industry_category': '創新板股票', 'stock_id': '68..."
322,6873,泓德能源,創新版股票,twse,2024-11-25,"{'industry_category': '創新版股票', 'stock_id': '68..."
2138,6873,泓德能源,綠能環保,twse,2025-09-30,"{'industry_category': '綠能環保', 'stock_id': '687..."
416,6902,GOGOLOOK-創,創新版股票,twse,2024-12-04,"{'industry_category': '創新版股票', 'stock_id': '69..."
649,6902,GOGOLOOK-創,創新板股票,twse,2025-05-16,"{'industry_category': '創新板股票', 'stock_id': '69..."
2007,6902,GOGOLOOK,數位雲端,twse,2025-09-30,"{'industry_category': '數位雲端', 'stock_id': '690..."
109,8080,永利聯合,電子零組件業,tpex,2022-06-03,"{'industry_category': '電子零組件業', 'stock_id': '8..."
1429,8080,泰霖,建材營造,tpex,2025-09-30,"{'industry_category': '建材營造', 'stock_id': '808..."
270,8087,華鎂鑫,光電業,tpex,2023-07-05,"{'industry_category': '光電業', 'stock_id': '8087..."
1564,8087,麗升能源,綠能環保類,tpex,2025-09-30,"{'industry_category': '綠能環保類', 'stock_id': '80..."
278,8476,台境,其他,tpex,2023-07-05,"{'industry_category': '其他', 'stock_id': '8476'..."
287,8476,台境,綠能環保類,tpex,2023-11-02,"{'industry_category': '綠能環保類', 'stock_id': '84..."
1609,8476,台境*,綠能環保,twse,2025-09-30,"{'industry_category': '綠能環保', 'stock_id': '847..."

In [32]:
df_sorted = df.sort_values(['stock_id', 'list_date'])
df_latest = df_sorted.drop_duplicates(subset='stock_id', keep='last')

In [33]:
df_latest

,stock_id,stock_name,industry_category,list_type,list_date,raw
960,0050,元大台灣50,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0050..."
2760,0051,元大中型100,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0051..."
2761,0052,富邦科技,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0052..."
2762,0053,元大電子,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0053..."
716,0054,元大台商50,ETF,twse,2025-08-27,"{'industry_category': 'ETF', 'stock_id': '0054..."
...,...,...,...,...,...,...
3949,TAIEX,加權指數,大盤,twse,NaT,"{'industry_category': '大盤', 'stock_id': 'TAIEX..."
3972,TPEx,櫃買指數,大盤,tpex,NaT,"{'industry_category': '大盤', 'stock_id': 'TPEx'..."
3953,Textiles,紡織纖維類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Te..."
3955,Tourism,觀光事業類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'To..."
3974,TradingConsumersGoods,貿易百貨類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Tr..."

In [34]:
# 1) 一個名稱對到多個代號的名稱清單
dup_names = (df_latest.groupby('stock_name')['stock_id']
            .nunique().sort_values(ascending=False))
dup_names = dup_names[dup_names > 1]               # 只留 >1 的
print("重複名稱數量：", dup_names.shape[0])
print(dup_names)                             

# 2) 列出這些名稱對應的所有資料列（看清楚是哪幾個代號）
diff_rows = (df_latest[df_latest['stock_name'].isin(dup_names.index)]
             .sort_values(['stock_name','stock_id']))
diff_rows[['stock_name','stock_id','industry_category','list_type','list_date']].head(50)

重複名稱數量： 5
stock_name
億豐    2
永信    2
研揚    2
神達    2
致伸    2
Name: stock_id, dtype: int64

     stock_name stock_id industry_category list_type  list_date
1604         億豐     8464              居家生活      twse 2025-09-30
352          億豐     9915                其他      twse 2024-12-04
644          永信     1716             生技醫療業      twse 2025-04-30
3426         永信     3705             生技醫療業      twse 2025-09-30
414          研揚     2463          電腦及週邊設備業      twse 2024-12-04
1883         研揚     6579          電腦及週邊設備業      twse 2025-09-30
445          神達     2315              電子工業      twse 2024-12-04
3428         神達     3706          電腦及週邊設備業      twse 2025-09-30
380          致伸     2336          電腦及週邊設備業      twse 2024-12-04
1069         致伸     4915            電子零組件業      twse 2025-09-30

In [35]:
df3 = df_latest.copy()

In [36]:
df3

,stock_id,stock_name,industry_category,list_type,list_date,raw
960,0050,元大台灣50,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0050..."
2760,0051,元大中型100,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0051..."
2761,0052,富邦科技,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0052..."
2762,0053,元大電子,ETF,twse,2025-09-30,"{'industry_category': 'ETF', 'stock_id': '0053..."
716,0054,元大台商50,ETF,twse,2025-08-27,"{'industry_category': 'ETF', 'stock_id': '0054..."
...,...,...,...,...,...,...
3949,TAIEX,加權指數,大盤,twse,NaT,"{'industry_category': '大盤', 'stock_id': 'TAIEX..."
3972,TPEx,櫃買指數,大盤,tpex,NaT,"{'industry_category': '大盤', 'stock_id': 'TPEx'..."
3953,Textiles,紡織纖維類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Te..."
3955,Tourism,觀光事業類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'To..."
3974,TradingConsumersGoods,貿易百貨類指數,Index,twse,NaT,"{'industry_category': 'Index', 'stock_id': 'Tr..."

In [37]:
df3.drop(columns='raw',inplace=True)

In [38]:
df3

                   stock_id stock_name industry_category list_type  list_date
960                    0050     元大台灣50               ETF      twse 2025-09-30
2760                   0051    元大中型100               ETF      twse 2025-09-30
2761                   0052       富邦科技               ETF      twse 2025-09-30
2762                   0053       元大電子               ETF      twse 2025-09-30
716                    0054     元大台商50               ETF      twse 2025-08-27
...                     ...        ...               ...       ...        ...
3949                  TAIEX       加權指數                大盤      twse        NaT
3972                   TPEx       櫃買指數                大盤      tpex        NaT
3953               Textiles    紡織纖維類指數             Index      twse        NaT
3955                Tourism    觀光事業類指數             Index      twse        NaT
3974  TradingConsumersGoods    貿易百貨類指數             Index      twse        NaT

[2996 rows x 5 columns]

In [39]:
df3.to_csv("cleaned_stock_info.csv")

In [40]:
# seperate index data

In [ ]:
df_index = df3[df3['industry_category']=='Index']
df_index.to_csv("index_list.csv", index=False, encoding="utf-8-sig")

:

In [ ]:
df_index